name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/devchaudhary666/cicd-app:latest \
            --build-arg APP_VERSION=v1 .

      - name: Push to GitHub Registry
        run: |
          docker push ghcr.io/devchaudhary666/cicd-app:latest

      - name: Deploy to k3s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/cicd-app -n production
